### ISSUE TITLE
Only team`s users can view own teams

### ISSUE THREAD

**Issue by alexsnowb** [alexsnowb/crm-on-laravel#5]

**Comment by SayedSajadHosseini** [comment]
hey, would you like to assign it to me?

**Comment by alexsnowb** [comment]
> hey, would you like to assign it to me?

Of course)

**Comment by SayedSajadHosseini** [comment]
can you describe a little detail about this issue?

**Comment by alexsnowb** [comment]
Teams have users. Users can see only they personal teams now.
via \app\Http\Livewire\Team\Index.php
```
            'teams' => Team::where('user_id', Auth::id())
```
It is necessary for user to see teams in which he is a member.
They are also linked through the table 'team_user'

**Comment by SayedSajadHosseini** [comment]
Okay, but where to show to?
in the following own team?

**Comment by alexsnowb** [comment]
Here \app\Http\Controllers\TeamsController.php
```
Route::resource('/dashboard/teams', TeamsController::class)
    ->middleware(['auth:sanctum', 'verified'])
```
